export const CONST_VALS = {
    TIMEOUT: 5000,
    NUM_OF_PLAYERS: 4,
    LIST_OF_PLAYERS: 'LIST_OF_PLAYERS',
    LIST_OF_CURRENT_PLAYERS: 'LIST_OF_CURRENT_PLAYERS',
    DECK_INFO: 'DECK_INFO',
    DEFAULT_COINS: 5000,
    COINS_LOSS_PER_ROUND: 900,
}